import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, Link2, Copy, Check, ChevronDown } from 'lucide-react';
import { toast } from 'sonner';
import type { NicheAnalysisResult } from '@/hooks/useNicheAnalysis';

interface ExportMenuProps {
  data: NicheAnalysisResult;
  dashboardRef: React.RefObject<HTMLDivElement>;
}

const ExportMenu = ({ data, dashboardRef }: ExportMenuProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const { jsPDF } = await import('jspdf');

      if (!dashboardRef.current) {
        throw new Error('Dashboard element not found');
      }

      const canvas = await html2canvas(dashboardRef.current, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#000000',
        logging: false,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = pageWidth - 20;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      // Add header
      pdf.setFillColor(0, 0, 0);
      pdf.rect(0, 0, pageWidth, 20, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.text('NichePulse AI Analysis Report', 10, 13);
      pdf.setFontSize(8);
      pdf.text(new Date().toLocaleDateString(), pageWidth - 30, 13);

      // Add image content
      let yPosition = 25;
      let remainingHeight = imgHeight;
      let sourceY = 0;

      while (remainingHeight > 0) {
        const availableHeight = pageHeight - yPosition - 10;
        const sliceHeight = Math.min(availableHeight, remainingHeight);
        const sourceHeight = (sliceHeight / imgHeight) * canvas.height;

        if (sourceY > 0) {
          pdf.addPage();
          yPosition = 10;
        }

        pdf.addImage(
          imgData,
          'PNG',
          10,
          yPosition,
          imgWidth,
          sliceHeight,
          undefined,
          'FAST'
        );

        sourceY += sourceHeight;
        remainingHeight -= sliceHeight;
        yPosition = 10;
      }

      pdf.save(`nichepulse-${data.query.replace(/\s+/g, '-')}-${Date.now()}.pdf`);
      toast.success('PDF exported successfully!');
    } catch (error) {
      console.error('PDF export failed:', error);
      toast.error('Failed to export PDF');
    } finally {
      setIsExporting(false);
      setIsOpen(false);
    }
  };

  const handleCopyLink = () => {
    const params = new URLSearchParams({
      q: data.query,
      p: data.platform,
      s: data.style,
    });
    const shareUrl = `${window.location.origin}?${params.toString()}`;
    
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    toast.success('Share link copied to clipboard!');
    
    setTimeout(() => {
      setCopied(false);
      setIsOpen(false);
    }, 1500);
  };

  const handleCopyResults = () => {
    const results = `
NichePulse AI Analysis Report
============================
Query: ${data.query}
Platform: ${data.platform}
Style: ${data.style}

NICHE SCORECARD
---------------
Market Saturation: ${data.scorecard.marketSaturation}%
Growth Potential: ${data.scorecard.growthPotential}%
Gap Score: ${data.scorecard.gapScore}%

TOP OUTLIER CREATORS
--------------------
${data.outliers.map((o, i) => `${i + 1}. ${o.name} (@${o.niche})
   Followers: ${o.followers.toLocaleString()} | Avg Views: ${o.avgViews.toLocaleString()}
   View/Follower Ratio: ${o.viewToFollowerRatio}x
   Insight: ${o.insight}`).join('\n\n')}

CONTENT IDEAS
-------------
${data.contentIdeas.map((idea, i) => `${i + 1}. ${idea.title}
   ${idea.description}
   Est. Views: ${idea.estimatedViews} | Difficulty: ${idea.difficulty}`).join('\n\n')}

VIRAL HOOKS
-----------
${data.viralHooks.map((hook, i) => `${i + 1}. "${hook.text}" (${hook.hookType})`).join('\n')}

Generated by NichePulse AI on ${new Date().toLocaleDateString()}
`.trim();

    navigator.clipboard.writeText(results);
    toast.success('Results copied to clipboard!');
    setIsOpen(false);
  };

  return (
    <div className="relative">
      <motion.button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-secondary text-foreground text-sm font-medium"
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
      >
        <Download className="w-4 h-4" />
        <span>Export</span>
        <ChevronDown className={`w-4 h-4 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
      </motion.button>

      <AnimatePresence>
        {isOpen && (
          <>
            <motion.div
              className="fixed inset-0 z-40"
              onClick={() => setIsOpen(false)}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            />
            <motion.div
              className="absolute right-0 mt-2 w-56 glass-card overflow-hidden z-50"
              initial={{ opacity: 0, y: -10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -10, scale: 0.95 }}
              transition={{ duration: 0.15 }}
            >
              <div className="py-2">
                <button
                  onClick={handleExportPDF}
                  disabled={isExporting}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left text-sm text-muted-foreground hover:bg-secondary/50 hover:text-foreground transition-colors disabled:opacity-50"
                >
                  <Download className="w-4 h-4" />
                  <span>{isExporting ? 'Exporting...' : 'Download as PDF'}</span>
                </button>
                
                <button
                  onClick={handleCopyLink}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left text-sm text-muted-foreground hover:bg-secondary/50 hover:text-foreground transition-colors"
                >
                  {copied ? (
                    <Check className="w-4 h-4 text-success" />
                  ) : (
                    <Link2 className="w-4 h-4" />
                  )}
                  <span>{copied ? 'Copied!' : 'Copy Share Link'}</span>
                </button>
                
                <button
                  onClick={handleCopyResults}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left text-sm text-muted-foreground hover:bg-secondary/50 hover:text-foreground transition-colors"
                >
                  <Copy className="w-4 h-4" />
                  <span>Copy as Text</span>
                </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ExportMenu;
